### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by budlight** [Lispython/human_curl#39]
It appears curl2 also needs python 3 support

**Comment by magicgoose** [comment]
+1
It appears impossible to install human_curl with pip3

```
$ pip3 install human_curl
Collecting human-curl
  Downloading human_curl-0.1.9.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 33kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/32/xwqqzsys6jz_l6bcw077b7hh0000gn/T/pip-build-npwr4wuc/human-curl/setup.py", line 27
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
```

**Comment by gstaniak** [comment]
Bump up. I've just been bitten by the same thing.

Is this project active? It looks great with its 'requests' compatibility, an easy way to use curl capabilities without changing habits (too much). I tried to make it run under 3.6 but looks like that's too complex for my limited knowledge of Python.

**Comment by infosisio** [comment]
Bump up.

**Comment by magicgoose** [comment]
> Is this project active?

> Latest commit 1bdda95 on Mar 6, 2016

**Comment by Ammadkhalid** [comment]
Sounds like we got no choice.
